# Generated by Django 3.2 on 2021-06-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
