# Generated by Django 3.2 on 2021-06-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0004_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
