# Generated by Django 3.2 on 2021-06-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0008_auto_20210617_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='course_image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='image_s',
            new_name='student_image',
        ),
    ]
