# Generated by Django 3.2 on 2021-06-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0010_rename_student_image_student_image_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image_s',
            new_name='student_image',
        ),
    ]
