# Generated by Django 3.2 on 2021-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0015_alter_grade_grade_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_0',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
