# Generated by Django 3.2 on 2021-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0017_auto_20210624_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(4, '4.5'), (1, '3.0'), (0, '2.0'), (2, '3.5'), (3, '4.0'), (5, '5.0')], default=0),
        ),
    ]
