# Generated by Django 3.2 on 2021-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0018_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student_course',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(4, '4.5'), (2, '3.5'), (5, '5.0'), (3, '4.0'), (1, '3.0'), (0, '2.0')], default=0),
        ),
    ]
