# Generated by Django 3.2 on 2021-06-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0020_auto_20210624_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(3, '4.0'), (0, '2.0'), (2, '3.5'), (1, '3.0'), (4, '4.5'), (5, '5.0')], default=0),
        ),
        migrations.CreateModel(
            name='Student2_course_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.student2')),
            ],
        ),
    ]
