# Generated by Django 3.2 on 2021-06-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0024_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('3.5', '3.5'), ('5.0', '5.0'), ('4.5', '4.5'), ('2.0', '2.0'), ('3.0', '3.0'), ('4.0', '4.0')], default=2.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='student2_course_grade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.student2_course'),
        ),
    ]
