# Generated by Django 3.2 on 2021-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0026_auto_20210624_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('5.0', '5.0'), ('2.0', '2.0'), ('4.0', '4.0'), ('3.5', '3.5'), ('4.5', '4.5'), ('3.0', '3.0')], default=2.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='student2_course_grade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
