# Generated by Django 3.2 on 2021-06-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0031_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('4.5', '4.5'), ('5.0', '5.0'), ('4.0', '4.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5')], default=2.0, max_length=3),
        ),
    ]
