# Generated by Django 3.2 on 2021-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0033_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('3.0', '3.0'), ('5.0', '5.0'), ('2.0', '2.0'), ('4.5', '4.5'), ('4.0', '4.0'), ('3.5', '3.5')], default=2.0, max_length=3),
        ),
        migrations.DeleteModel(
            name='Student2_course_grade',
        ),
    ]
