# Generated by Django 3.2 on 2021-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0039_auto_20210625_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(5, '5.0'), (2, '3.5'), (1, '3.0'), (3, '4.0'), (0, '2.0'), (4, '4.5')], default=0),
        ),
    ]
