# Generated by Django 3.2 on 2021-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0040_alter_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student2_course_grade',
            name='aaa',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, '2.0'), (3, '4.0'), (4, '4.5'), (2, '3.5'), (1, '3.0'), (5, '5.0')], default=0),
        ),
    ]
