# Generated by Django 3.2 on 2021-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0046_auto_20210626_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[(4, '4.5'), (0, '2.0'), (2, '3.5'), (1, '3.0'), (5, '5.0'), (3, '4.0')], default=2.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='student2_course_grade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
