# Generated by Django 3.2 on 2021-06-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0048_alter_grade_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student2_course_grade',
            new_name='Student_course_grade',
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[(1, '3.0'), (4, '4.5'), (3, '4.0'), (2, '3.5'), (5, '5.0'), (0, '2.0')], default=2.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.student'),
        ),
    ]
