# Generated by Django 3.2 on 2021-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0049_auto_20210626_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students_image')),
            ],
        ),

    ]
