# Generated by Django 3.2 on 2021-06-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0051_auto_20210626_2008'),
    ]

    operations = [


    ]
