# Generated by Django 3.2 on 2021-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0004_auto_20210626_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='dziennikweb.Student_course_grade', to='dziennikweb.Course'),
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='grade',
            field=models.CharField(choices=[('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5')], default=2.0, max_length=3),
        ),
    ]
