# Generated by Django 3.2 on 2021-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0005_auto_20210626_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course_grade',
            name='grade',
            field=models.CharField(choices=[('4.0', '4.0'), ('4.5', '4.5'), ('3.5', '3.5'), ('2.0', '2.0'), ('3.0', '3.0'), ('5.0', '5.0')], default=2.0, max_length=3),
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='student_course_grade',
            unique_together={('course', 'student')},
        ),
    ]
