# Generated by Django 3.2 on 2021-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0012_alter_student_course_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='album',
            field=models.CharField(blank=True, default='007', max_length=32),
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='grade',
            field=models.CharField(choices=[('3.0', '3.0'), ('5.0', '5.0'), ('4.5', '4.5'), ('2.0', '2.0'), ('4.0', '4.0'), ('3.5', '3.5')], default=2.0, max_length=3),
        ),
    ]
