# Generated by Django 3.2 on 2021-07-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0015_auto_20210704_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='grade',
            field=models.CharField(choices=[('4.0', '4.0'), ('2.0', '2.0'), ('3.0', '3.0'), ('5.0', '5.0'), ('4.5', '4.5'), ('3.5', '3.5')], default=2.0, max_length=3),
        ),
    ]
