# Generated by Django 3.2 on 2021-06-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='courses_image')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[(2, '3.5'), (4, '4.5'), (5, '5.0'), (1, '3.0'), (3, '4.0'), (0, '2.0')], default=2.0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students_image')),
                ('courses', models.ManyToManyField(blank=True, default='', to='dziennikweb.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student_course_grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennikweb.student')),
            ],
        ),
    ]
