# Generated by Django 3.2 on 2021-07-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennikweb', '0014_alter_student_course_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='student_course_grade',
            name='grade',
            field=models.CharField(choices=[('5.0', '5.0'), ('3.5', '3.5'), ('3.0', '3.0'), ('4.5', '4.5'), ('4.0', '4.0'), ('2.0', '2.0')], default=2.0, max_length=3),
        ),
    ]
